In [1]:
import numpy as np

In [2]:
a = np.random.random(4)
print(a)

[0.47246483 0.62945821 0.97048482 0.36097099]


numpy中的max方法

In [3]:
max = np.max(a)
print(max)

0.9704848194380966


argmax:找到最大值对应的索引编号

In [4]:
index = np.argmax(a)
print(index)

2


In [5]:
a = np.random.random(size = (4,4))
print(a)

[[0.11084358 0.25401425 0.2696956  0.18911972]
 [0.22466707 0.47335181 0.86618423 0.657908  ]
 [0.48120538 0.15820628 0.03059064 0.7100855 ]
 [0.54992485 0.00234826 0.90428832 0.23908728]]


In [6]:
# axis = 1:表示横轴   axis = 0：纵轴
max_row = np.max(a, axis = 1)
print(max_row)

[0.2696956  0.86618423 0.7100855  0.90428832]


In [7]:
max_column = np.max(a, axis = 0)
print(max_column)

[0.54992485 0.47335181 0.90428832 0.7100855 ]


In [8]:
max = np.max(a)
print(max)

0.904288322796047


In [ ]:
max = np.max(a, axis = (0)
print(max)