numpy：计算，数学工具

In [1]:
import numpy as np                 #import:导入模块，库   as：别名

In [2]:
#创建一个2行4列的数组，并指定数组都是int类型，且全部初始化为1
one = np.ones(shape = (2,4), dtype = int)
print(one)

[[1 1 1 1]
 [1 1 1 1]]


广播

In [3]:
six = one + 5
print(six)

[[6 6 6 6]
 [6 6 6 6]]


In [4]:
four = six - 2
print(four)

[[4 4 4 4]
 [4 4 4 4]]


In [5]:
ten = four * 2.5
print(ten)

[[10. 10. 10. 10.]
 [10. 10. 10. 10.]]


In [6]:
#产生一个三维数组，（2，3，4）  arange(24):产生0~23个整数，共24个
a = np.arange(24).reshape(2, 3, 4)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [7]:
print(a.shape)

(2, 3, 4)


In [8]:
#产生3行4列的0~1之间的浮点随机数
weight = np.random.random(size = (3, 4))

In [9]:
print(weight)

[[0.07193435 0.83440359 0.67749191 0.06870411]
 [0.11200209 0.53576316 0.57897154 0.03672228]
 [0.95289738 0.32662769 0.77934403 0.63001608]]


In [10]:
weight_a = a * weight
print(weight_a)

[[[ 0.          0.83440359  1.35498381  0.20611232]
  [ 0.44800837  2.6788158   3.47382921  0.25705599]
  [ 7.62317903  2.93964921  7.79344031  6.93017689]]

 [[ 0.86321222 10.84724671  9.48488667  1.03056158]
  [ 1.79203346  9.10797373 10.42148763  0.69772339]
  [19.05794758  6.85918148 17.14556868 14.49036986]]]


In [11]:
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [12]:
#   逗号前：操作行  逗号后：操作列
#相当于裁剪图片
print(a[1:3, :])

[[ 4  5  6  7]
 [ 8  9 10 11]]


In [13]:
print(a[0, :])

[0 1 2 3]


In [14]:
a = np.arange(16).reshape(4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [15]:
print(a[::2, ::2])

[[ 0  2]
 [ 8 10]]


In [16]:
a = np.arange(36).reshape(6,6) - 18
print(a)

[[-18 -17 -16 -15 -14 -13]
 [-12 -11 -10  -9  -8  -7]
 [ -6  -5  -4  -3  -2  -1]
 [  0   1   2   3   4   5]
 [  6   7   8   9  10  11]
 [ 12  13  14  15  16  17]]


In [17]:
a = a.astype(float)

In [18]:
a[a>0] = np.log(a[a>0])
a[a<0] = np.abs(a[a<0])

In [19]:
print(a)

[[18.         17.         16.         15.         14.         13.        ]
 [12.         11.         10.          9.          8.          7.        ]
 [ 6.          5.          4.          3.          2.          1.        ]
 [ 0.          0.          0.69314718  1.09861229  1.38629436  1.60943791]
 [ 1.79175947  1.94591015  2.07944154  2.19722458  2.30258509  2.39789527]
 [ 2.48490665  2.56494936  2.63905733  2.7080502   2.77258872  2.83321334]]
