In [1]:
import numpy as np

In [2]:
a = np.arange(9).reshape(3, 3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [3]:
mask = np.array([[0,1,0], [1,1,1], [0,1,0]], dtype = bool)
print(mask)

[[False  True False]
 [ True  True  True]
 [False  True False]]


In [4]:
zero = np.zeros(shape=(3,3), dtype=int)
print(zero)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [5]:
zero[mask] = a[mask]

In [6]:
print(zero)

[[0 1 0]
 [3 4 5]
 [0 7 0]]
