In [1]:
import numpy as np

In [2]:
a = np.random.random(size = 5)
b = np.random.random(size = (2, 4))
print(a)
print("-------------------------------------------------")
print(b)

[0.50056632 0.38226493 0.37514939 0.83783288 0.20310233]
-------------------------------------------------
[[0.85247295 0.99658145 0.33737234 0.37046714]
 [0.85871882 0.00653745 0.02704048 0.45653709]]


In [3]:
print(np.maximum.accumulate(a))

[0.50056632 0.50056632 0.50056632 0.83783288 0.83783288]


In [4]:
print(np.maximum.accumulate(b))

[[0.85247295 0.99658145 0.33737234 0.37046714]
 [0.85871882 0.99658145 0.33737234 0.45653709]]


In [5]:
print(np.maximum.accumulate(b, axis = 1))

[[0.85247295 0.99658145 0.99658145 0.99658145]
 [0.85871882 0.85871882 0.85871882 0.85871882]]


In [6]:
print(np.minimum.accumulate(b, axis = 1))

[[0.85247295 0.85247295 0.33737234 0.33737234]
 [0.85871882 0.00653745 0.00653745 0.00653745]]
